#! /bin/sh
rm -f .error$$
ERROR=0
export PATH="$PATH" LANG=C
if test "$NO_COLOR" = 1 ; then
(make V=1 "$@" 2>&1 || touch .error$$)
else
(make V=1 "$@" 2>&1 || touch .error$$)| ./extras/buildsystem/make.pl
fi
test -f .error$$ && ERROR=1
rm -f .error$$
exit $ERROR
